name: Deploy Documentation to GitHub Pages

on:
    workflow_dispatch:
    pull_request:
      types: [closed]
      paths:
        - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  

      - name: Install dependencies
        run: |
          pip install -r requirements.txt 
          pip install sphinx sphinx-rtd-theme sphinx-autodoc-typehints

      - name: Build Documentation
        run: |
          sphinx-build -b html docs/source docs/build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: docs/build
